name: New Tag On main branch
on:
  push:
    tags:
      - rel.*
jobs:
  Echo-Variables:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi! The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Hi! This job is now running on a ${{ runner.os }} server hosted byt GitHub!"
      - run: echo "Hi! The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Hi! The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Hi! The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Hi! This job's status is ${{ job.status }}."

